/**
 * Multi-Page PDF Report Generator for StudyFlow
 * Team: Salah Uddin Kader & Sohana Rahman
 */

const sendEmail = require('./sendEmail');

/**
 * Generate multi-page HTML report with proper page breaks
 */
const generateReportHTML = (userData) => {
    const {
        name = 'Student',
        email,
        totalSessions = 0,
        totalMinutes = 0,
        completedTasks = 0,
        pendingTasks = [],
        achievements = 0,
        subjects = [],
        recentSessions = [],
        tier = 'Bronze'
    } = userData;

    const hours = Math.floor(totalMinutes / 60);
    const minutes = totalMinutes % 60;

    // Split subjects into pages (5 per page)
    const subjectPages = [];
    for (let i = 0; i < subjects.length; i += 5) {
        subjectPages.push(subjects.slice(i, i + 5));
    }

    return `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <style>
                @page { size: A4; margin: 20mm; }
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .page { page-break-after: always; padding: 40px; min-height: 900px; }
                .page:last-child { page-break-after: auto; }
                .header { text-align: center; border-bottom: 3px solid #667eea; padding-bottom: 20px; margin-bottom: 30px; }
                .header h1 { color: #667eea; font-size: 32px; margin: 10px 0; }
                .stats-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 30px 0; }
                .stat-box { padding: 20px; border: 2px solid #667eea; border-radius: 10px; text-align: center; }
                .stat-value { font-size: 36px; font-weight: bold; color: #667eea; }
                .stat-label { font-size: 14px; color: #666; text-transform: uppercase; margin-top: 5px; }
                .section { margin: 30px 0; }
                .section-title { color: #667eea; font-size: 22px; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; margin-bottom: 20px; }
                .item { padding: 12px; background: #f8fafc; margin-bottom: 10px; border-left: 4px solid #667eea; border-radius: 5px; }
                .footer { text-align: center; padding-top: 20px; border-top: 2px solid #e2e8f0; color: #666; font-size: 12px; }
            </style>
        </head>
        <body>
            
            <!-- PAGE 1: Overview -->
            <div class="page">
                <div class="header">
                    <div style="font-size: 48px;">📊</div>
                    <h1>StudyFlow Progress Report</h1>
                    <p style="color: #666; margin: 5px 0;">${name} | ${email}</p>
                    <p style="color: #999; font-size: 14px;">${new Date().toLocaleDateString()}</p>
                </div>

                <div class="stats-grid">
                    <div class="stat-box">
                        <div class="stat-value">${totalSessions}</div>
                        <div class="stat-label">Focus Sessions</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${hours}h ${minutes}m</div>
                        <div class="stat-label">Total Study Time</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${completedTasks}</div>
                        <div class="stat-label">Tasks Completed</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-value">${tier}</div>
                        <div class="stat-label">Current Tier</div>
                    </div>
                </div>

                <div class="section">
                    <h2 class="section-title">Key Achievements</h2>
                    <div class="item">
                        <strong>🏆 Total Achievements:</strong> ${achievements} unlocked
                    </div>
                    <div class="item">
                        <strong>📈 Study Consistency:</strong> ${totalSessions > 0 ? 'Active learner' : 'Getting started'}
                    </div>
                    <div class="item">
                        <strong>⭐ Performance Tier:</strong> ${tier} - Keep pushing forward!
                    </div>
                </div>

                <div class="footer">
                    <strong>Page 1</strong> | Generated by StudyFlow<br/>
                    Salah Uddin Kader • Sohana Rahman
                </div>
            </div>

            ${subjectPages.length > 0 ? subjectPages.map((pageSubjects, pageIndex) => `
            <!-- PAGE ${pageIndex + 2}: Subject Performance ${pageIndex + 1} -->
            <div class="page">
                <div class="header">
                    <h1>📚 Subject Performance</h1>
                    <p style="color: #666;">Detailed breakdown of study hours by subject</p>
                </div>

                <div class="section">
                    ${pageSubjects.map(sub => `
                        <div class="item">
                            <div style="display: flex; justify-content: space-between; align-items: center;">
                                <span style="font-weight: bold; font-size: 16px;">${sub.name}</span>
                                <span style="color: #667eea; font-weight: bold; font-size: 18px;">${sub.hours || 0} hours</span>
                            </div>
                            ${sub.sessions ? `<div style="color: #666; font-size: 14px; margin-top: 5px;">${sub.sessions} sessions completed</div>` : ''}
                        </div>
                    `).join('')}
                </div>

                <div class="footer">
                    <strong>Page ${pageIndex + 2}</strong> | Subject Analysis ${pageIndex + 1}<br/>
                    studyflow.salahuddin.codes
                </div>
            </div>
            `).join('') : ''}

            ${pendingTasks.length > 0 ? `
            <!-- PAGE: Pending Tasks -->
            <div class="page">
                <div class="header">
                    <h1>📋 Pending Tasks</h1>
                    <p style="color: #666;">Tasks requiring your attention</p>
                </div>

                <div class="section">
                    ${pendingTasks.slice(0, 15).map(task => `
                        <div class="item">
                            <strong>${task.title}</strong>
                            <div style="font-size: 13px; color: #666; margin-top: 5px;">
                                Priority: <span style="color: ${task.priority === 'high' ? '#e53e3e' : task.priority === 'medium' ? '#dd6b20' : '#805ad5'};">${task.priority || 'normal'}</span>
                                ${task.subject ? ` | Subject: ${task.subject}` : ''}
                            </div>
                        </div>
                    `).join('')}
                </div>

                <div class="footer">
                    <strong>Page ${subjectPages.length + 2}</strong> | Task Overview<br/>
                    studyflow.salahuddin.codes
                </div>
            </div>
            ` : ''}

            <!-- FINAL PAGE: Summary -->
            <div class="page">
                <div class="header">
                    <h1>✨ Report Summary</h1>
                </div>

                <div class="section">
                    <h2 class="section-title">Overall Progress</h2>
                    <p style="font-size: 16px; line-height: 1.8;">
                        <strong>${name}</strong>, you've completed <strong>${completedTasks}</strong> tasks 
                        across <strong>${totalSessions}</strong> focus sessions, accumulating 
                        <strong>${hours} hours and ${minutes} minutes</strong> of productive study time.
                    </p>
                    <p style="font-size: 16px; line-height: 1.8; margin-top: 15px;">
                        You've unlocked <strong>${achievements}</strong> achievements and reached the 
                        <strong>${tier}</strong> tier. Keep up the excellent work!
                    </p>
                </div>

                <div class="section">
                    <h2 class="section-title">Next Steps</h2>
                    <div class="item">✅ Continue maintaining your study schedule</div>
                    <div class="item">✅ Focus on ${pendingTasks.length > 0 ? 'completing pending tasks' : 'adding new goals'}</div>
                    <div class="item">✅ Track your progress regularly in the analytics dashboard</div>
                </div>

                <div style="margin-top: 50px; padding: 25px; background: #f8fafc; border: 2px solid #667eea; border-radius: 10px; text-align: center;">
                    <p style="font-size: 18px; color: #667eea; font-weight: bold; margin: 0 0 10px;">Generated by StudyFlow Team</p>
                    <p style="margin: 5px 0; color: #666;">Salah Uddin Kader - Developer</p>
                    <p style="margin: 5px 0; color: #666;">Sohana Rahman - Admin</p>
                    <p style="margin: 15px 0 0; font-size: 12px; color: #999;">
                        <a href="https://studyflow.salahuddin.codes" style="color: #667eea; text-decoration: none;">studyflow.salahuddin.codes</a>
                    </p>
                </div>
            </div>

        </body>
        </html>
    `;
};

/**
 * Send multi-page report via email
 */
const sendReportEmail = async (userData, options = {}) => {
    try {
        const reportHTML = generateReportHTML(userData);
        
        await sendEmail({
            email: userData.email,
            subject: `📊 StudyFlow Report - ${new Date().toLocaleDateString()}`,
            heading: 'Your Progress Report',
            preheader: `${userData.totalSessions} sessions, ${Math.floor(userData.totalMinutes / 60)}h study time`,
            message: reportHTML,
            ctaLabel: 'View Dashboard',
            url: options.dashboardUrl || process.env.FRONTEND_URL
        });

        console.log('✅ Multi-page report sent to:', userData.email);
        return { success: true };
    } catch (error) {
        console.error('❌ Report send failed:', error.message);
        throw error;
    }
};

/**
 * PDF metadata for download
 */
const generatePDFMetadata = (userData) => {
    return {
        title: `StudyFlow Report - ${userData.name}`,
        author: 'Salah Uddin Kader & Sohana Rahman',
        subject: 'Progress Report',
        creator: 'StudyFlow'
    };
};

module.exports = {
    generateReportHTML,
    sendReportEmail,
    generatePDFMetadata
};
